In [45]:
import os
import pandas as pd

api_key = os.getenv('CM_API_KEY') # Obtain the API key from environment variable.

In [46]:
from coinmetrics.api_client import CoinMetricsClient

client = CoinMetricsClient(api_key)

In [47]:
my_markets = client.reference_data_markets(
    ).to_dataframe()
my_markets

,market,exchange,type,base,quote,pair,pool_config_id,contract_address,price_includes_fee,variable_fee,...,status,strike,option_contract_type,is_european,order_taker_fee,order_maker_fee,multiplier_size,margin_trading_enabled,settlement_price,fee
0,balancer_v2_eth-1-aave-ampl_eth-spot,balancer_v2_eth,spot,aave,ampl_eth,aave-ampl_eth,1,6b0d50a9df06006170e2d11d468cbfe0f58b43e2,False,False,...,NaN,<NA>,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
1,balancer_v2_eth-1-aave-crv-spot,balancer_v2_eth,spot,aave,crv,aave-crv,1,3b40d7d5ae25df2561944dd68b252016c4c7b280,True,False,...,NaN,<NA>,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
2,balancer_v2_eth-1-aave-usdt_eth-spot,balancer_v2_eth,spot,aave,usdt_eth,aave-usdt_eth,1,bd3a698826d27563d08d459faff2d5f6960e21cf,False,False,...,NaN,<NA>,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
3,balancer_v2_eth-1-alcx-axs_1_eth-spot,balancer_v2_eth,spot,alcx,axs_1_eth,alcx-axs_1_eth,1,7bf521b4f4c1543a622e11ee347efb1a23743322,False,False,...,NaN,<NA>,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
4,balancer_v2_eth-1-ape-axs_2_eth-spot,balancer_v2_eth,spot,ape,axs_2_eth,ape-axs_2_eth,1,5757b37098d65b097cbcb78e22ae862817a82702,False,False,...,NaN,<NA>,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
529331,zb.com-zb-usdt-spot,zb.com,spot,zb,usdt,zb-usdt,<NA>,NaN,<NA>,<NA>,...,NaN,<NA>,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
529332,zb.com-zkn-usdt-spot,zb.com,spot,zkn,usdt,zkn-usdt,<NA>,NaN,<NA>,<NA>,...,NaN,<NA>,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
529333,zb.com-zrx-btc-spot,zb.com,spot,zrx,btc,zrx-btc,<NA>,NaN,<NA>,<NA>,...,NaN,<NA>,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
529334,zb.com-zrx-qc-spot,zb.com,spot,zrx,qc,zrx-qc,<NA>,NaN,<NA>,<NA>,...,NaN,<NA>,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
529335,zb.com-zrx-usdt-spot,zb.com,spot,zrx,usdt,zrx-usdt,<NA>,NaN,<NA>,<NA>,...,NaN,<NA>,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>

In [48]:
# kraken futures
df = my_markets.loc[
    (my_markets.exchange=='kraken') &
    (my_markets.type=='future') &
    (my_markets.base.isin(['btc', 'eth']))
]
df

,market,exchange,type,base,quote,pair,pool_config_id,contract_address,price_includes_fee,variable_fee,...,status,strike,option_contract_type,is_european,order_taker_fee,order_maker_fee,multiplier_size,margin_trading_enabled,settlement_price,fee
397044,kraken-FF_ETHUSD_230728-future,kraken,future,eth,usd,eth-usd,<NA>,NaN,<NA>,<NA>,...,NaN,<NA>,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
397045,kraken-FF_ETHUSD_230825-future,kraken,future,eth,usd,eth-usd,<NA>,NaN,<NA>,<NA>,...,NaN,<NA>,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
397046,kraken-FF_ETHUSD_230929-future,kraken,future,eth,usd,eth-usd,<NA>,NaN,<NA>,<NA>,...,NaN,<NA>,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
397047,kraken-FF_ETHUSD_231027-future,kraken,future,eth,usd,eth-usd,<NA>,NaN,<NA>,<NA>,...,NaN,<NA>,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
397048,kraken-FF_ETHUSD_231124-future,kraken,future,eth,usd,eth-usd,<NA>,NaN,<NA>,<NA>,...,NaN,<NA>,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
397354,kraken-FI_XBTUSD_250926-future,kraken,future,btc,usd,btc-usd,<NA>,NaN,<NA>,<NA>,...,NaN,<NA>,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
397541,kraken-PF_ETHUSD-future,kraken,future,eth,usd,eth-usd,<NA>,NaN,<NA>,<NA>,...,NaN,<NA>,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
397797,kraken-PF_XBTUSD-future,kraken,future,btc,usd,btc-usd,<NA>,NaN,<NA>,<NA>,...,NaN,<NA>,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
397819,kraken-PI_ETHUSD-future,kraken,future,eth,usd,eth-usd,<NA>,NaN,<NA>,<NA>,...,NaN,<NA>,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
397821,kraken-PI_XBTUSD-future,kraken,future,btc,usd,btc-usd,<NA>,NaN,<NA>,<NA>,...,NaN,<NA>,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>

In [49]:
availability = client.catalog_market_candles_v2(
    markets=list(df.market),
).to_dataframe().merge(df)
availability.loc[availability.frequency=='1m', ['market', 'expiration', 'min_time', 'max_time', 'base']].sort_values(by=['expiration'], ascending=False)

,market,expiration,min_time,max_time,base
1512,kraken-FI_XBTUSD_250926-future,2025-09-26 15:00:00+00:00,2025-03-10 14:16:00+00:00,2025-04-04 09:22:00+00:00,btc
1048,kraken-FI_ETHUSD_250926-future,2025-09-26 15:00:00+00:00,2025-03-24 09:22:00+00:00,2025-04-04 09:22:00+00:00,eth
288,kraken-FF_ETHUSD_250926-future,2025-09-26 08:00:00+00:00,2025-02-28 12:09:00+00:00,2025-04-04 09:22:00+00:00,eth
584,kraken-FF_XBTUSD_250926-future,2025-09-26 08:00:00+00:00,2025-02-24 08:21:00+00:00,2025-04-04 09:22:00+00:00,btc
1040,kraken-FI_ETHUSD_250627-future,2025-06-27 15:00:00+00:00,2024-11-29 23:35:00+00:00,2025-04-04 09:22:00+00:00,eth
...,...,...,...,...,...
592,kraken-FI_ETHUSD_200925-future,2020-09-25 16:00:00+00:00,2020-09-09 11:07:00+00:00,2020-10-25 14:52:00+00:00,eth
1520,kraken-PF_ETHUSD-future,NaT,2023-02-20 12:48:00+00:00,2025-04-04 09:22:00+00:00,eth
1528,kraken-PF_XBTUSD-future,NaT,2023-02-20 12:50:00+00:00,2025-04-04 09:22:00+00:00,btc
1536,kraken-PI_ETHUSD-future,NaT,2020-09-09 11:15:00+00:00,2025-04-04 09:22:00+00:00,eth
1544,kraken-PI_XBTUSD-future,NaT,2020-09-09 11:34:00+00:00,2025-04-04 09:22:00+00:00,btc

`min_time` is the datetime when that value is first available. see below for a way to convert this to Eastern.

In [50]:
# Create a DatetimeIndex for every day until 2035
all_days = pd.date_range(start='2025-01-01', end='2035-12-31')

# Convert to DataFrame for easier filtering and grouping
df = pd.DataFrame({'date': all_days})

df['year'] = df['date'].dt.year
df['month'] = df['date'].dt.month

# Filter to only include Fridays (where weekday=4)
fridays_only = df[df['date'].dt.weekday == 4]

# Group by year, month and get the last Friday of each month
last_fridays = fridays_only.groupby(['year', 'month']).last()
last_fridays

                 date
year month
2025 1     2025-01-31
     2     2025-02-28
     3     2025-03-28
     4     2025-04-25
     5     2025-05-30
...               ...
2035 8     2035-08-31
     9     2035-09-28
     10    2035-10-26
     11    2035-11-30
     12    2035-12-28

[132 rows x 1 columns]

In [51]:
# predict the expiration of a month in the future...
month = 10
year = 2025

last_fridays.loc[year, month]

date   2025-10-31
Name: (2025, 10), dtype: datetime64[ns]

In [52]:
# deribit futures
df = my_markets.loc[
    (my_markets.exchange=='deribit') &
    (my_markets.type=='future') &
    (my_markets.base.isin(['btc', 'eth']))
]
df

,market,exchange,type,base,quote,pair,pool_config_id,contract_address,price_includes_fee,variable_fee,...,status,strike,option_contract_type,is_european,order_taker_fee,order_maker_fee,multiplier_size,margin_trading_enabled,settlement_price,fee
125230,deribit-BTC-10DEC21-future,deribit,future,btc,usd,btc-usd,<NA>,NaN,<NA>,<NA>,...,NaN,<NA>,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
125567,deribit-BTC-10FEB23-future,deribit,future,btc,usd,btc-usd,<NA>,NaN,<NA>,<NA>,...,NaN,<NA>,NaN,<NA>,0.0005,-0.0001,<NA>,<NA>,<NA>,<NA>
125959,deribit-BTC-10JAN25-future,deribit,future,btc,usd,btc-usd,<NA>,NaN,<NA>,<NA>,...,NaN,<NA>,NaN,<NA>,0.0005,-0.0001,<NA>,<NA>,<NA>,<NA>
126243,deribit-BTC-10JUN22-future,deribit,future,btc,usd,btc-usd,<NA>,NaN,<NA>,<NA>,...,NaN,<NA>,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
126363,deribit-BTC-10MAR17-future,deribit,future,btc,usd,btc-usd,<NA>,NaN,<NA>,<NA>,...,NaN,<NA>,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
302969,deribit-ETH-9JUN23-future,deribit,future,eth,usd,eth-usd,<NA>,NaN,<NA>,<NA>,...,NaN,<NA>,NaN,<NA>,0.0005,-0.0001,<NA>,<NA>,<NA>,<NA>
304194,deribit-ETH-9SEP22-future,deribit,future,eth,usd,eth-usd,<NA>,NaN,<NA>,<NA>,...,NaN,<NA>,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
304283,deribit-ETH-PERPETUAL-future,deribit,future,eth,usd,eth-usd,<NA>,NaN,<NA>,<NA>,...,NaN,<NA>,NaN,<NA>,0.0005,0.0,<NA>,<NA>,<NA>,<NA>
304284,deribit-ETH_USDC-PERPETUAL-future,deribit,future,eth,usdc,eth-usdc,<NA>,NaN,<NA>,<NA>,...,NaN,<NA>,NaN,<NA>,0.0005,0.0,<NA>,<NA>,<NA>,<NA>
304285,deribit-ETH_USDT-PERPETUAL-future,deribit,future,eth,usdt,eth-usdt,<NA>,NaN,<NA>,<NA>,...,NaN,<NA>,NaN,<NA>,0.0005,0.0,<NA>,<NA>,<NA>,<NA>

In [53]:
availability = client.catalog_market_candles_v2(
    markets=list(df.market),
).to_dataframe().merge(df)
availability.loc[availability.frequency=='1m', ['market', 'expiration', 'min_time', 'max_time', 'base']].sort_values(by=['expiration'], ascending=False)

,market,expiration,min_time,max_time,base
1270,deribit-BTC-27MAR26-future,2026-03-27 08:00:00+00:00,2025-03-28 08:13:00+00:00,2025-04-04 09:22:00+00:00,btc
3252,deribit-ETH-27MAR26-future,2026-03-27 08:00:00+00:00,2025-03-28 08:38:00+00:00,2025-04-04 09:22:00+00:00,eth
3140,deribit-ETH-26DEC25-future,2025-12-26 08:00:00+00:00,2024-12-27 08:34:00+00:00,2025-04-04 09:22:00+00:00,eth
1118,deribit-BTC-26DEC25-future,2025-12-26 08:00:00+00:00,2024-12-27 08:13:00+00:00,2025-04-04 09:22:00+00:00,btc
3196,deribit-ETH-26SEP25-future,2025-09-26 08:00:00+00:00,2024-09-27 12:55:00+00:00,2025-04-04 09:22:00+00:00,eth
...,...,...,...,...,...
2118,deribit-BTC_USDC-PERPETUAL-future,NaT,2022-03-09 13:01:00+00:00,2025-04-04 09:22:00+00:00,btc
2126,deribit-BTC_USDT-PERPETUAL-future,NaT,2023-12-14 14:23:00+00:00,2025-04-04 09:22:00+00:00,btc
3964,deribit-ETH-PERPETUAL-future,NaT,2019-03-14 13:03:00+00:00,2025-04-04 09:22:00+00:00,eth
3972,deribit-ETH_USDC-PERPETUAL-future,NaT,2022-03-14 13:01:00+00:00,2025-04-04 09:22:00+00:00,eth
3980,deribit-ETH_USDT-PERPETUAL-future,NaT,2023-12-14 12:29:00+00:00,2025-04-04 09:22:00+00:00,eth

In [54]:
# remaining spot
df = my_markets.loc[
    (my_markets.exchange.isin(['kraken', 'coinbase'])) &
    (my_markets.type=='spot') &
    (my_markets.base.isin(['btc', 'eth'])) &
    (my_markets.quote=='usd')
]
df

,market,exchange,type,base,quote,pair,pool_config_id,contract_address,price_includes_fee,variable_fee,...,status,strike,option_contract_type,is_european,order_taker_fee,order_maker_fee,multiplier_size,margin_trading_enabled,settlement_price,fee
109789,coinbase-btc-usd-spot,coinbase,spot,btc,usd,btc-usd,<NA>,NaN,<NA>,<NA>,...,online,<NA>,NaN,<NA>,<NA>,<NA>,<NA>,False,<NA>,<NA>
109908,coinbase-eth-usd-spot,coinbase,spot,eth,usd,eth-usd,<NA>,NaN,<NA>,<NA>,...,online,<NA>,NaN,<NA>,<NA>,<NA>,<NA>,False,<NA>,<NA>
398016,kraken-btc-usd-spot,kraken,spot,btc,usd,btc-usd,<NA>,NaN,<NA>,<NA>,...,NaN,<NA>,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
398151,kraken-eth-usd-spot,kraken,spot,eth,usd,eth-usd,<NA>,NaN,<NA>,<NA>,...,NaN,<NA>,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>

In [55]:
availability = client.catalog_market_candles_v2(
    markets=list(df.market),
).to_dataframe().merge(df)
availability.loc[availability.frequency=='1m', ['market', 'expiration', 'min_time', 'max_time', 'base']].sort_values(by=['expiration'], ascending=False)

,market,expiration,min_time,max_time,base
0,coinbase-btc-usd-spot,NaT,2014-12-01 05:33:00+00:00,2025-04-04 09:22:00+00:00,btc
8,coinbase-eth-usd-spot,NaT,2016-05-18 00:14:00+00:00,2025-04-04 09:22:00+00:00,eth
16,kraken-btc-usd-spot,NaT,2013-10-06 21:34:00+00:00,2025-04-04 09:22:00+00:00,btc
24,kraken-eth-usd-spot,NaT,2015-08-07 14:03:00+00:00,2025-04-04 09:22:00+00:00,eth

In [56]:
availability.min_time.dt.tz_convert('US/Eastern')

0    2014-12-01 00:33:00-05:00
1    2014-12-01 00:30:00-05:00
2    2014-12-01 00:30:00-05:00
3    2014-12-01 00:30:00-05:00
4    2014-12-01 00:30:00-05:00
5    2014-12-01 00:00:00-05:00
6    2014-11-30 23:00:00-05:00
7    2014-11-30 19:00:00-05:00
8    2016-05-17 20:14:00-04:00
9    2016-05-17 20:10:00-04:00
10   2016-05-17 20:10:00-04:00
11   2016-05-17 20:00:00-04:00
12   2016-05-17 20:00:00-04:00
13   2016-05-17 20:00:00-04:00
14   2016-05-17 20:00:00-04:00
15   2016-05-17 20:00:00-04:00
16   2013-10-06 17:34:00-04:00
17   2013-10-06 17:30:00-04:00
18   2013-10-06 17:30:00-04:00
19   2013-10-06 17:30:00-04:00
20   2013-10-06 17:30:00-04:00
21   2013-10-06 17:00:00-04:00
22   2013-10-06 16:00:00-04:00
23   2013-10-05 20:00:00-04:00
24   2015-08-07 10:03:00-04:00
25   2015-08-07 10:00:00-04:00
26   2015-08-07 10:00:00-04:00
27   2015-08-07 10:00:00-04:00
28   2015-08-07 10:00:00-04:00
29   2015-08-07 10:00:00-04:00
30   2015-08-07 08:00:00-04:00
31   2015-08-06 20:00:00-04:00
Name: min_time, dtype: datetime64[ns, US/Eastern]